</$objtype/mkfile

TARG=tl

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	thumb.$O\
	compat.$O\

HFILES=\
	l.h\
	../5c/5.out.h\
	../cc/compat.h\

BIN=/$objtype/bin
</sys/src/cmd/mkone

../5c/enam.c: ../5c/5.out.h
	@ { cd ../5c; mk enam.c }

enam.$O:	../5c/enam.c
	$CC $CFLAGS ../5c/enam.c

compat.$O:	../cc/compat
