</sys/doc/fonts

default:V: sam.ps sam.pdf samtut.ps samtut.pdf

sam.ps:D:	sam.ms fig1.ps fig2.ps fig3.ps fig4.ps fig5.pic fig6.pic fig7.pic refs
	{echo $FONTS; cat sam.ms refs} | pic | tbl | troff -ms -mpictures | lp -dstdout >sam.ps
	../cleanps sam.ps

samtut.ps:D:	sam.tut
	troff -ms $prereq | dpost > samtut.ps
	../cleanps samtut.ps

%.pdf:D: %.ps
	cat ../docfonts $stem.ps >_$stem.ps
	# distill _$stem.ps && mv _$stem.pdf $stem.pdf
	ps2pdf _$stem.ps $stem.pdf && rm -f _$stem.ps

sam.trout:D:	sam.ms fig1.ps fig2.ps fig3.ps fig4.ps fig5.pic fig6.pic fig7.pic refs
	{echo $FONTS; cat sam.ms refs} | pic | tbl | troff -ms -mpictures >sam.trout

sam.html:D:	sam.ms fig1.ps fig2.ps fig3.ps fig4.ps fig5.pic fig6.pic fig7.pic refs
	pic sam.ms refs | tbl | htmlroff -ms -mhtml >sam.html

clean:V:
	rm -f sam.ps sam.pdf sam*.png sam.html samtut.pdf samtut.ps
