</$objtype/mkfile
BIN=/$objtype/bin/auth
HFILES =\
	SConn.h\
	secstore.h\

OFILES =\
	pak.$O\
	password.$O\
	SConn.$O\
	util.$O\


TARG = secstore secstored secuser aescbc	# descbc
DEBUG = secchk

default:V: all

$O.aescbc: aescbc.$O
	$LD -o $target $prereq
$O.descbc: descbc.$O util.$O
	$LD -o $target $prereq

$O.secstore: secstore.$O  $OFILES
	$LD -o $target $prereq

$O.secstored: secstored.$O dirls.$O secureidcheck.$O $OFILES
	$LD -o $target $prereq

$O.secuser: secuser.$O $OFILES
	$LD -o $target $prereq

secstore.$O secstored.$O $OFILES: $HFILES

secureidcheck.$O: ../secureidcheck.c
	$CC $CFLAGS ../secureidcheck.c

# debugging
$O.secchk: secchk.$O secureidcheck.$O
	$LD -o $target $prereq

</sys/src/cmd/mkmany
