.LP
.ce
.ps 16
.CW
THE BAD STUDENT
.R
 
.ps 8
.CW
tags: 1969, frankie_willard, prince, tab2, cheryl
.R

.PP
.ps 10
I tear a sheet from my notebook.  After some fidgeting I manage to
produce a cigarette.  I lean back against the concrete wall of the
building, my rat\-tail poking into the scruff of my neck.  It's rather
uncomfortable.  There is a commotion from somewhere, over near the
basketball courts.  After a brief period of silence, the school bell
rings.  I curse, sub\-audibly, taking my place in line.  I'm careful not
to crumple the cigarette as I conceal it within my sleeve.
.PP
.ps 10
Recess is over.
.PP
.ps 10
I'm antsy.  I shift my weight from one leg to the other.  This
jostling brings to mind Frankie Willard, made to stand with both feet
planted inside of a single tile on the floor.  Punishment for having
spoken out of turn.  Frankie complained that because of his great size,
he would surely topple over if he were not permitted to sway from side
to side.  The teacher sarcastically denied his request\(emstructural
integrity be damned.  No, Frankie would have to stand firmly within the
square, maintaining his posture for the duration of the class.  At the
time, I too had regarded Frankie's claims as spurious.  Does an office
building need to sway from side to side?  It seemed ridiculous.  A man
should be able to stand still.
.PP
.ps 10
Today I'm of a mind to view Frankie's situation in a different
light.  Standing still in this line is impossible.  Despite myself, I've
begun to sway from side to side.  Fuck it, Frankie was right all along.
.PP
.ps 10
At the moment, no one is watching me.  I disregard protocol and
resume my cigarette.  Smoke slinks from the burning cherry, a string of
ten\-dimensional nothingness.  Or so I choose to perceive.
.PP
.ps 10
The boy in front of me rotates his head to an obtuse azimuth, asks
to bum a cig.  I am more than happy to oblige.  From my pocket I produce
two slender folds of paper, offering one to my companion.  He's still
in possession of the lighter I made for him, so we're all set.  Good to
go.  From time to time, I'm happy to supply free product, as a short
demonstration will often serve to spark demand.  When one's business is
illicit, establishing the perception of good\-natured magnanimity is
wise.  Happy customers are quiet customers.
.PP
.ps 10
And quiet is a baseline necessity for my mission.

.PP
.ps 10
Just as the fresh cigarette taste is making itself apparent, our
teacher pokes her head around the corner.  She notices us stragglers,
lately fallen away from the back of the line.  She's displeased to note
that we're still here, leaning up against the wall, each man enjoying
an individual smoke.  She approaches swiftly and proceeds to bend our
ears.  That's when she realizes who I am.  Quite comically, this new
awareness halts her scolding, mid\-sentence.  She directs the other boys
back to the classroom and then turns to me, a stupid look on her face.
She pulls me by my rat\-tail into a deserted corridor.  The contact is
exhilarating.
.PP
.ps 10
I'm going to score.
.PP
.ps 10
The woman has been shooting me these kinds of looks all semester.  A
couple of times she's caught me adjusting my visor, straining to catch
a peek through her blouse.  Instead of voicing an objection she usually
just smiles.  It's crossed my mind that she may even
.I
fancy
.R
my attempts
to look down her shirt.  Consider: she's the only one of our first
grade teachers who will wear shorts in summer.  To my knowledge, this
is technically against the rules.  I turn these thoughts over in my
mind, one after the other, as I consider my immediate future.
.PP
.ps 10
She tightens her grip on my shoulder.
.PP
.ps 10
I brace for a kiss.
.PP
.ps 10
Instead, she snatches the cigarette from my lips and sends it
careening over her shoulder, skittering down the corridor.  Well, that
wasn't quite what I expected.  I think to myself that it's convenient
this corner of the building is devoid of traffic.  Could she have
planned our confrontation days, even weeks, in advance?  Have things
really progressed to that level?  Gradually, the woman is drawing my
attention to infinite new dimensions, threading my string through
myriad vortices, the resulting matrix a blunt satire of our
tessellating material realm.
.I
She's
.R
the teacher?  I'm fit to burst.

.PP
.ps 10
She parts her lips as if to speak.  Softly, softly.
.PP
.ps 10
This must be it.
.PP
.ps 10
"So.  You believe that folding pieces of paper into the shape of a
.I
cigarette,
.R
then
.I
selling
.R
them to your classmates is a good way to
make
.I
friends,
.R
Thomas?"
.PP
.ps 10
The tenderness I sensed only moments before is now vanished.  She's
trying her best to be stern.  I can't say why, exactly, but this only
excites me more.
.PP
.ps 10
"So far it seems to be working fine," I offer, straining, barely
containing myself.  "I have plenty of friends."
.PP
.ps 10
"I've seen you outside, pretending to smoke, for weeks now.  The
students here look up to you, and I'm disappointed in how you've
chosen to repay that trust.  I want you to think of how you're
influencing them, Thomas."
.PP
.ps 10
"I'm not coercing anyone," I correct gently, so as not to rend the
gossamer fragility of the moment.  "I'm simply providing a service.
There's an obvious demand and I'm only too happy to fill it.  Surely
you realize, this sort of equitable transaction is the very basis of
our free economy, which ensures the continuity of\(em"
.PP
.ps 10
She kisses me.

.PP
.ps 10
I break free.
.PP
.ps 10
"\(emthe very
.I
continuance
.R
of our society."
.PP
.ps 10
She doesn't seem impressed with my argument.
.PP
.ps 10
From my jacket I produce a conspicuously pristine piece of
equipment.  The object fairly leaps from its place of concealment.  She
is somewhat startled, tries to mask her reaction, but the sudden
adoration evident in her eyes will not be suppressed.  Does she know
what this is, then, after all?   Removing her hand slowly from my own,
I raise the object to my chest (her waist) and finger the switch that
brings it to life.  She jumps as a holographic image grows out of my
palm.  I have to adjust my visor again before I'm able to see it.
.PP
.ps 10
So, this is Prince Rogers Nelson.  Not exactly an imposing figure,
but in relation to his framing, here in my hand, it hardly matters.
Reports indicate that my teacher is quite enamored with this miniature
entertainer.  By all rights he was a fine composer, but some say he
actually considered himself to be the physical reincarnation of the
Egyptian Pharaoh
.I
Ahkanaten.
.R
There was a spate of controversy around
the time he decided to found his own religion.
.PP
.ps 10
Whatever.
.PP
.ps 10
The unexpected appearance of the tiny man seems to be doing the
trick with my teacher.  As PRN begins to vibrate, I angle him beneath
her skirt.
.PP
.ps 10
"Just lay back," says Prince.
.PP
.ps 10
She does as he says.
.PP
.ps 10
While she is momentarily stunned, distracted, I remove the
remaining contraband from my pockets, depositing several paper
cigarettes onto the window ledge behind me.  Shortly thereafter, the
spring breeze carries them away, floating them ever downwards, towards
the unnaturally green summer grass of the courtyard.  All evidence of
my wrongdoing thus disposed of, I snap closed my gadget and switch to
manual, gazing deeply into my teacher's eyes as I finish her off.
.PP
.ps 10
She's some time in coming.  But once sated, her body goes slack.  At
last, I relax my arm and place my hand on her exquisite breast.
.PP
.ps 10
To my great surprise, she recoils.  It seems I have ventured too
far.  She smiles awkwardly and pushes me away, leans her head out of
the window to see what I've been up to all this time she's been
writhing under the ministrations of the holographic Prince.  Her face
shoots completely red, full of blood.  The view from the window, of
course, is unremarkable, but it's not the landscaping below that
concerns her.  She sees the paper cigarettes scattered about the
courtyard and deduces that they must belong to me.
.PP
.ps 10
She begins to lecture me.  Even these playthings, which are not real
at all, still set a negative example for the other students.  Such toys
glorify the act of real smoking.  I should have known better than to
engage in this sort of thing while at school.  The premises is also a
commerce restricted zone, blah blah blah, etc.  She is scrupulous to
avoid any mention of her orgasm, though I sense the experience is
still very much on her mind.
.PP
.ps 10
Overall, it proves to be a lackluster brow\-beating.  I consider the
context of present events set against the larger backdrop of my
mission and decide that her appraisal of my behavior is irrelevant.  At
twelve years of age, infiltrating the first grade has been a cakewalk.
If this doesn't boost my grade average I don't know what will.  I
swear, I'm ready to graduate CU/FARLEY.  Let's hope my father and the
Chief see things my way.
.PP
.ps 10
I acknowledge her statements as I shove my hand into my pants and
scratch my groin.
.PP
.ps 10
As we return to the classroom, I reach out to hold her hand.
.PP
.ps 10
I probably don't have to tell you that I use the same hand.
