.LP
.ce
.ps 16
.CW
UBICOMP
.R
 
.ps 8
.CW
tags: 1969, potus, tab1
.R

.PP
.ps 10
There is a ring of teeth around my stick and I can't pull it out.  I
ease back and forth, gently, but the mouth won't let go.  A sliver of
saliva escapes, spreading first around my stick's circumference, then
down to its base.  All at once the President's head starts to move
again.
.PP
.ps 10
Textbook package delivery.  Six calories of Turing gel forced into
the digestive track of the mark.  Freed from its carriage, some of the
payload has already bonded firmly with the President's teeth.
Presently, the liquid bootstraps itself into the machinery of
surveillance.  All logged in, phase one is complete.  Other components
of the payload make their way into the President's circulatory system,
compensating for various biological ticks that would otherwise prove
fatal to the Commander In Chief.  Phase two, loaded, completed.
.PP
.ps 10
I imagine there is something of an alkaline flavor.  I don't know
how she can stand it.
.PP
.ps 10
Without warning, an additional teaspoon\-dollop of nutrient\-rich
paste shoots between the President's lips.  Slowly, it threads down her
esophagus, coating her stomach's lining.  I swish my stick around a
bit, making sure that the gel, by now teaming with expensive hardware,
gets a fair chance to take hold.  She murmurs softly.  I assume in
pleasure.
.PP
.ps 10
I glance at my watch.
.PP
.ps 10
Over time, the rogue cells I've introduced will create new tissue.
They'll get into the business of subverting dendrite structures, which
in turn (I'm told) will lead to the President's conscious assent to
our programs.
.PP
.ps 10
.I
Caveat:
.R
the gel will need to be administered on a regular basis.  I
assume I will be selected as the agent of delivery (it's of no concern
either way\(emthere are numerous agents who are up to the task).  In
any case, the process will continue.  Before the President knows what
is happening, she will begin to
.I
crave
.R
the injections, find herself
inexplicably drawn to the blunt insertion of stick into mouth.  Lacking
awareness, she'll come to regard the process as a pleasure of her own
devising.  She may even develop an affinity for the taste.
.PP
.ps 10
But enough of my speculation, however well\-informed.  Her mouth is
upon me now, showing no sign of loosening its grip.  Not losing
suction.  Her eyes have rolled back into her head.  She's become
unresponsive.  Even her gag reflex has gone dead.
.PP
.ps 10
As an initial response to insertion, this
.I
faux
.R
catatonic state is
not unusual.  In my field\-work I've observed that women will often slip
into semi\-consciousness once they've worked the Turing gel past their
back teeth.  In truth, I was quite alarmed the first time it happened.
Maybe I had dribbled psychoactive sedative onto the tip of my cock, I
thought to myself.  But no, this brief period of unconsciousness tends
to be shallow, tends to pass quickly.
.PP
.ps 10
I decide to sneak a peek, to see how she's coming along.  Her mouth
glides smoothly on a thick lather of saliva, sealed by the walls of
her throat.  Her head bobs up and down, gently rotating, rhythmically
advancing and retreating across the length of my equipment.  She's
quite awake now and seems to have swallowed her cares.
.PP
.ps 10
A strand of the President's hair has caught on my watchband, but
I'm reluctant to interrupt her work.
.PP
.ps 10
I nudge her lovingly on the ear and her entire head shifts weight
to the other side.  Her eyes flick open and she smiles as she releases
my stick, seemingly unaware of the considerable amount of time that
has passed.  I slide out, drawing a trail of spit between myself and
her tongue, which she stares at quizzically before flashing a
mischievous grin and then aggressively chewing it all back into her
mouth.  Ordinarily this would be fine, but a pool of spittle has
coalesced around my scrotum, and now it traces the contour of my
buttocks.  It is cold.
.PP
.ps 10
A pink square blips in the lower\-left of my vision, telling me that
the Turing cells have gained purchase.
.PP
.ps 10
I engage the President verbally as she re\-applies her lipstick and
adjusts her
.I
coiffure.
.R
.PP
.ps 10
I start making excuses, looking for a way out of the room.
