.LP
.ce
.ps 16
.CW
THE PARTISAN
.R
 
.ps 8
.CW
tags: 1949, 1950, 1951, 1953, 1954, mother, tab1
.R

.ps 10
.ce
.B
1
.R
.PP
.ps 10
Mother didn't love me.
.PP
.ps 10
Well, who knows, but it sure was hard to tell.  I assume she wanted
me gone by graduation.  Pushing me out of the nest fit symmetrically
with first having introduced me to its warmth.
.PP
.ps 10
Only, I hadn't needed to be pushed.
.PP
.ps 10
Whatever the case, I wouldn't have stuck around once I'd secured my
means of escape.  In fact, my childhood agenda came to center upon
vacating the nest at the earliest possible convenience.  I told her as
much on a handful of occasions, which may have been an early source of
her resentment towards me.
.PP
.ps 10
Drifting, there.  Such thoughts are useless for filling out my
report.
.PP
.ps 10
I dribble a handful of words into the document and save before
making a trip to the men's room.  Time to call it a night.
.PP
.ps 10
Passing through the marketing department, I ponder the desks of the
new\-hires, noticing for the first time that their cubicle partitions
and arm\-thick contract binders serve as ballast against the
accumulation of personal effects.  The design is intentional.  In my
first few months at the company I never would have suspected such
subtle architectures of control.
.PP
.ps 10
I round the corner to the men's room and take a seat in the
furthest stall.
.PP
.ps 10
After a few minutes I'm faced with a problem.
.PP
.ps 10
No toilet paper.
 
.ce
.B
2
.R
 
.PP
.ps 10
I am out of work.
.PP
.ps 10
Real work, that is.  My study group has been shut down.
.PP
.ps 10
It's the Greens.  They're everywhere.  Though admittedly they're less
numerous than in recent years.
.PP
.ps 10
Take my former manager.  Matters of consequence on his mind.  A month
ago he retracted our billet after deciding that my group had fielded
too many atheists.  A security risk, he said.
.PP
.ps 10
What is this, the 1910s?
.PP
.ps 10
For a while now I've been sitting at home, steadily freezing solid
in my poorly insulated study.  Not the best working environment, and
I'm not getting much done.  On top of it all, Mother won't leave me
alone.  I've had to resist the urge to flag her for rendition.  I like
to think I've made the right decision.
.PP
.ps 10
This morning I discover that the Greens have cut loose my former
manager.  I'm digging around in his account when the call comes in.
.PP
.ps 10
We're back on.
.PP
.ps 10
Patent disputes in the hinterlands.
.PP
.ps 10
The traffic orb on my desk glows a suggestive blue as I pick up the
phone to contact my team.
 
.ce
.B
3
.R
 
.PP
.ps 10
Well, that didn't last long.
.PP
.ps 10
Back to retail.
.PP
.ps 10
I work the counter between calls because no one else knows how to
operate the products we sell.  Customers roll in and then they roll
back out,
.I
au gratin
.R
waves of body fat wrapped in plastic garments.
The typical specimen reeks of a public cafeteria.
.PP
.ps 10
A man wanders into my zone and starts fidgeting with the boxes of
electronic equipment.  He picks up a box and then sets it back down
without examining it.  He repeats this awkward choreography at several
different positions along the aisle.  His movements seem aimless and
there appears to be no intelligent pattern underlying his
investigations.
.PP
.ps 10
What is going on here?  The answer is that I don't care.
.PP
.ps 10
"Is there something I can assist you with, sir?"
.PP
.ps 10
Contractually, I cannot allow his anti\-commercial behavior to pass
unchallenged.  I maneuver myself between him and the shelves and then
read him one of the scripts I've been required to memorize.
.PP
.ps 10
 "I am certified in twenty\-seven dialects of formal sales
semantics, with a top\-five ranking amongst appliance technicians in
the local Green.  It would be my pleasure to interpret your needs
today.  Thank you for choosing AT&T\f(CW™\fR."
.PP
.ps 10
"Son, let me ask you a question.  Do you actually
.I
like
.R
working
here?"
.PP
.ps 10
I have to admit, there's no easy way to answer.  I don't let it show
on my face.
.PP
.ps 10
From an obscured storage pouch the man produces a business card and
communicates it smoothly into my hand.  Affixed to its underside is a
thousand dollar bill.  I turn the tiny rectangle in my hand, staring at
it quizzically.  What has just happened here?  Gradually, I realize that
the currency is fraudulent.  The thousand dollar bill is a facsimile,
printed on the reverse of the business card.  I smile and the man
lights up, returning my grin.  I swear I can hear his face skipping
gears.
.PP
.ps 10
"Five minutes of your time and that t\-note becomes real, deposits
into the account of your choice.  Spend it however you like."
.PP
.ps 10
It's hardly pocket change, and of course I'm well beyond broke, so
I gesture for him to proceed with his pitch.
.PP
.ps 10
Before I know it, he has me filling out paperwork, signing papers.
"Signing your life away," he announces, and smiles.
.PP
.ps 10
He doesn't seem to care about my previous experience.

.ce
.B
4
.R
 
.PP
.ps 10
I'm being sent to the front.
.PP
.ps 10
Well,
.I
one
.R
of the fronts.
.PP
.ps 10
In modern warfare, someone has to keep the breathers running.  My
orders are to install hotfixes and updates on the machines that
control the mobile flow tanks, which in turn feed the breathers.  We
aren't permitted to install unauthorized programs, but everyone I've
ever worked with does so anyway.
.PP
.ps 10
Our Sergeant hosts a fileserver from his backpack.
.PP
.ps 10
The men of the platoon have taken to calling me "Mother." I assume
this is in reference to my careful maintenance of their breather
apparatuses.  I don't find it amusing in the slightest.
.PP
.ps 10
In spite of improvements to our equipment, signal degradation
continues to render the mail unreliable.  The satellite gear proved
flaky and we dumped it after the first week in the field.  At higher
elevations we're sometimes able to establish line of sight with the
fleet.
.PP
.ps 10
Mother would probably like to hear from me.  Maybe I'll drop her a
line the next time we're up the mountain.
.bp
.ce
.B
5
.R
 
.PP
.ps 10
Responding to aggressive stimuli, I discharge my service rifle into
the crowd.
.PP
.ps 10
My round exits the back of a man's skull and strikes the man
standing directly behind him.  It then travels on to the next man
standing behind him.  For a split second the perforated heads sync up,
their wounds aligning in a peculiar sort of optical tributary.  As
quickly as it is formed, the channel collapses and the illusion of
coherence is lost.
.PP
.ps 10
This dynamic tableaux has been observed by several hovering
cameras.  I'm struck by the way each unit edges past its neighbor,
vying for a better angle on the corpses lying at my feet.  They seem to
deliberately ignore me and my fellow soldiers.  I don't understand why.
.PP
.ps 10
A hand falls on my shoulder.  It is the Sergeant.
.PP
.ps 10
.I
What's he doing here,
.R
I think to myself.
.PP
.ps 10
Oh, right.
 
.ce
.B
6
.R
 
.PP
.ps 10
Prison clothing is uncomfortable.  In my case it fits well enough.
Some of my peers have been less fortunate.
.PP
.ps 10
I keep in step with the other prisoners.  Occasionally, I catch my
reflection in the back of another inmate's jacket.  Even out of uniform
we're unmistakably soldiers.
.PP
.ps 10
A guard shouts obscenities through a bullhorn and the man in front
of me stumbles.  I think that I recognize him.  Latino, approximately
twenty years of age.  Infantry, definitely.  Could it be?
.PP
.ps 10
When the guards aren't looking I kick him in the back.
.PP
.ps 10
"Keep up, asshole."
.PP
.ps 10
He gasps, flashing me the secret hand sign of our platoon.
.PP
.ps 10
I'm convinced now, and kick him again, this time less carefully.
Less the actor.  I have him on the ground by the time the guard with
the bullhorn interrupts.
.PP
.ps 10
.I
"Move,
.R
faggots!"
.PP
.ps 10
We do as he says.
.PP
.ps 10
The data has changed hands.
.bp
.ce
.B
7
.R
 
.PP
.ps 10
I am free.
.PP
.ps 10
Released.
.PP
.ps 10
The spring sun sinks into my face.  Mother has passed away at some
point during my incarceration.
.PP
.ps 10
I convalesce at home for two days before calling in to be
reactivated.
.PP
.ps 10
The boys will be anxious to hear about my experience behind bars.  I
wonder how many of us are left.
 
.ce
.B
8
.R
 
.PP
.ps 10
And now it's back to the grind.  Nothing has changed about the war
we've been fighting, though the locales tend to shift with the
seasons.  We manage the periodic disorientation by assigning colors to
each theater of operations.  This quarter we're in the Red.  The
projection is that by next quarter we'll be in the Black.
.PP
.ps 10
One of our little jokes.
.PP
.ps 10
Oh yes, and no White after Labor Day.
.PP
.ps 10
Staffing is flexible, pending new developments.  This rotation we're
at home.  For us, domestic deployment (as with training) constitutes
leave.  The boys are all present and we fall into our familiar rhythm
as we pace the perimeter Capitol Hill.
.PP
.ps 10
A froth of reporters churns to and fro between our lines.  The
latest fashion in Washington is a press pass that authorizes the
bearer to cross military checkpoints with impunity.  A stupid idea, to
be sure, but nobody asked my opinion.  The cameras flit about as a few
of the reporters spill over in my direction.
.PP
.ps 10
One approaches me, brandishing a microphone.
.PP
.ps 10
"Corporal!  What's your take on the continuance of the war?  Can you
give me seven syllables on the reinstatement of compulsory military
service?  The draft?"
.PP
.ps 10
I regard her from behind my service rifle.
.PP
.ps 10
Seven syllables?  Let's see.
.PP
.ps 10
"I'm afraid I enlisted."
