.LP
.vs 16 \" increase vertical spacing for title
.ce 2
.ps 16
.CW
HALF\-DANDY IN THE
RUBBISH FACTORY
.R
.vs 12 \" resume default vertical spacing
 
.ps 8
.CW
tags: 1918, lonnie, pennis_mold
.R

.PP
.ps 10
Standing in the mirror and seeing that without a belt, these new
slacks are simply not going to stay up.  I'm in danger of tipping the
balance between classical style and practicality, but I mustn't be
caught off guard if anyone should happen to catch a glimpse of me in
my civilian underclothes.  I find something suitable in my closet and
pin myself into the pants, clipping a handful of mesh transceivers to
my blouse before pulling on the pressure suit and chiming for a ride.
Down in the tunnels, I don't want my breeches coming loose, getting
wound around my legs inside of the suit.  Before exiting the apartment,
I remove a number of petals from a rose and press them between the
pages of my notebook.  I savor the scent for a few moments before
concealing the book within my pressure suit and heading out the door.
.PP
.ps 10
At the entrance to the lowest tunnels I pause before a monstrous
installation, a war machine from some forgotten conflict of decades
past, and affix my collapsed flower to a placard situated below the
airplane.  It is humid enough that the petals stick to its slick
surface with little effort.  Even in this diffuse lighting, the mighty
nose and wings of the plane gleam immodestly, and I am ashamed to
experience a wave of exhilaration, prostrate as I am before such a
reverential display of murderous articulation.  I gather myself and
proceed to the elevators.

.PP
.ps 10
In my mind it is all quite different than this.
.PP
.ps 10
I embody two discreet realities.  Suffering alone, I am continuously
in peril of favoring one reality over the other.  As of late, a new
barricade has been thrown up, an obstruction that permanently divides
these tandem perspectives of the rubbish factory.  Necessity demands
that I pick a side and entrench my position, but my heart cries out
for reconciliation.
.PP
.ps 10
I take solace in the fact that, being made of plaster, the dividing
wall will eventually bow under its own weight.
.PP
.ps 10
If memory serves, a similar plaster wall erected around the
masterpiece
IL CENACOLO\f(CW™\fR
protected it from the onslaught of mechanized
warfare, early in the last century.  No one expected a fresco to stand
against mortar fire, but here our fellow Leonardo had produced a hare
from his conical hat.  The wall stood firm though the building around
it crumbled to dust.
.PP
.ps 10
I see now that such a wall can be made to serve a useful purpose.
Do I really wish for all the evil in my thoughts to pass so freely?  It
is at moments such as these that I find it crucial to get something
down on paper, before mind's effluvium carries mind itself away on a
raft of sudden, fatiguing currents.  In truth, I write to cleanse the
palate.  There is a bad taste in my mouth after three weeks toiling on
the latest factory inventory.  Lonnie plays Microsoft SOLITAIRE\f(CW™\fR at his
desk while I scribble in my notebook.
.PP
.ps 10
Furthering my previous thought, let us now consider the plaster
wall in my mind as ballast.  A shift in perspective to interpret the
empty, unused spaces as the most precious of cargo: a portal to new
understanding.
.PP
.ps 10
I boot up a fresh sheet of paper, reflecting upon the true nature
of metaphor as filler.  A great sewer main has burst in my mind,
carrying forth copious amounts of shit and piss\(emboth having been
lodged quite stubbornly in the pipe.  This is the opposite of the wall.
I observe as each new parcel of feces floats away, bobbling down the
stream.  There is something that cannot be contained within a mind such
as my own, a mind that is slowly breaking up, dividing into dull, gray
cubicles.
.PP
.ps 10
It seems that we have come full circle.
.PP
.ps 10
Which way is it going to be, then?  Walls to divide, or portals to
connect?
.PP
.ps 10
They are both the same.  Textures that are defined, even as they are
described, by the perceiving apparatus.
.PP
.ps 10
There is a great wealth of surface detail to be absorbed, to be
sorted, and I do carry on exploring, but I find that there is only one
true form of currency, here in the rubbish factory, and that is the
universal reserve of the personal imagination.  It proves to be an
.I
aether
.R
that never devalues, that is never appraised relative to
markets or governments\(emit is the ineffable substance that
constitutes essential wealth.
.PP
.ps 10
Reaching this point of minor resolution, I close up my notebook and
stuff it into one of the compartments of my pressure suit.  A whistle
sounds, groaning, pixelated.  A gavel is banged and my mental courtroom
clears of solicitors, making room for me to think other thoughts, to
reconnect the cycling belt of my psyche back to the idling gears of
its cadaver.
.PP
.ps 10
It is time for lunch.

.PP
.ps 10
We men clamber into the mess hall, which has not yet reached fifty
percent capacity.  Two\- and three\-man teams are clotted into
flesh\-colored scabs around the edges of each steel table.  We dine on
whatever has been set down in front of us by the kitchen staff.
Between bites of supper, we trade raucous barbs.
.PP
.ps 10
"And what, pray tell, is the
.I
value
.R
of this thing called beauty," a
colleague stands up and asks, apparently to no one.
.PP
.ps 10
A few of the men turn around in their seats to face the speaker.
Some of them get up and leave altogether.  But most simply pick over
their lunch trays and stare at their food, seemingly oblivious to the
philosophical gauntlet that has been thrown down.
.PP
.ps 10
"Ah, yes, the
.I
dominant minority,"
.R
a familiar voice chimes in.
.PP
.ps 10
"Rather, I should say, an
.I
aristocracy of merit,"
.R
counters the
original speaker, earning smiles from every participating table.
.PP
.ps 10
I appreciate exchanges like this, here in the lunch room, as they
afford us men the chance to unwind between extended shifts in the
tunnels.  The work can be grueling, the hours long.  The repetitive
plunging of gloved hands or shielded feet into the crowded arteries of
the sanitation lines coarsens men to fellowship.  But here, we make our
own peace with our situation.  Here, we arrive on the cusp of our
destinies by the strain and sweat of our honest toil.  It is a kind of
progress.

.PP
.ps 10
Before things really get started, a triumvirate of management
stride into the room, enjoying a buffer nearly three meters in
diameter as they pass between the huddles of workmen.  I grip my lunch
tray with trepidation as they float past my table, unsure of the
purpose for their visit.
.PP
.ps 10
What I notice first is the impeccable styling of their attire.  Even
when down in the tunnels, these gentlemen always\(em\fIalways\fP\(emkeep
their gear clean.  In the general low\-light conditions of the sewer,
it is their bejeweled teeth and resplendent gold necklaces which can
first be seen approaching, glittering through the humid mists of
municipal waste.  At times, the ricocheting reflections may cause an
entire face to disappear, or at least, they may seem to disappear when
one's vision is obscured by a pressure suit mask.  But here in the mess
hall, we all remove our helmets to talk and eat.  Here, the glare does
not obscure but instead serves to illuminate.
.PP
.ps 10
The small group approaches now, my own supervisor striding to the
fore.  His low\-slung denim splits into a Cheshire grin of plaid cotton
undergarments.  The suede of my supervisor's sneakers appears to be
freshly brushed, having accumulated no floating particles of detritus
or dirt.  His tasteful, oversize polo tee asserts the classic dialectic
of red and white striping, situated masterfully alongside a deep blue
rectangle bearing numerous white stars, each of self\-evident, sacred
significance.  I am somewhat taken aback by this sudden explosion of
color.  It is a moment I cherish even as it overwhelms me, and I
briefly clench my eyelids together, attempting to trigger my mesh
camera, to stream the scene into the pages of my department's
distributed memory.

.PP
.ps 10
As the managers pass my table they hesitate, stop, and then double
back.
.PP
.ps 10
My supervisor's nostrils incline perceptibly.  As one, the group
turns to face me.  I swallow the food in my mouth, which goes down the
wrong way, and I begin to worry about the visible stubble on my face.
How must I appear to them?
.PP
.ps 10
"Yo, ya'll have been selected, son!  We're up in this place to
request that you authorize a temporary application fee of two billion
credits to secure your promotion to management.  Know what I'm sayin',
cousin?  To authenticate this ceremonial enhancement, please press
here, fool.  Fa sho."
.PP
.ps 10
I place my thumb onto the reader and press down, weakly.  This
elicits a further vocalization.
.PP
.ps 10
"Peace.  Five thousand, G."
.PP
.ps 10
And then they are gone.
.PP
.ps 10
I am quite literally bowled over, and my lunch tray pinwheels to
the floor in pursuit of my limp form.  Lonnie, faithful companion of lo
these many years, helps me back to my seat as I slowly regain my
composure.  Gradually, the ramifications of what has just happened
begin to sink in.  Promotion will mean an increase in my pension, new
quarters...  and an unlimited civilian clothing allowance.  I have just
been created anew.  Afforded a repeat birth.  I switch on all mesh
transceivers and begin capturing every possible angle of my
surroundings, preserving this vital moment, etching a record for the
corporate archives, for my descendants, for their inheritors.

.PP
.ps 10
"What up, son," Lonnie chides, adopting the formal tone of
management in a sort of mockery of their stiff, proper elocution.
"These negroes done lost they minds."
.PP
.ps 10
I nod my head slightly, acutely aware of the expanse that now
separates our respective circumstances.  The great plaster partition
has come crashing apart in my mind, and in this instant, the dejected,
isolated occupants of each chamber are crushed together, the sticks of
pious liberty bundled into a final, immobilizing unity.  I eschew my
former concerns, beholden as they were to considerations of slop and
waste.  The combustion of my thoughts is now fueled solely by the light
of its own countenance.
.PP
.ps 10
Lacking a prepared response, I yield to myself completely.
.PP
.ps 10
My face droops into my hand.  A bent elbow evenly supports the
increased weight of my skull, flesh and excessively powdered hair.  I
find that I have grown suddenly weary of contemplating the great
weight of my responsibility.  Lonnie will come to appreciate this
fatigue if ever he is called up, into the obdurate embrace of his
betters.
.PP
.ps 10
But at this moment I cannot expect him to fully understand.  Not
while he still finds himself tethered to the undercarriage of our
labyrinth of shifting human shit.
.PP
.ps 10
I look at him and it is obvious he cannot understand what I have
become.
.PP
.ps 10
"Dandy," I finally reply, employing the crude language of the
tunnels.  I burp towards the mess hall out of politeness.  In the
resulting silence I pick at the visor of my helmet.
.PP
.ps 10
Lonnie makes a face, forlorn, but still he says nothing.
.PP
.ps 10
I wave him away.  I excuse myself and leave my tray for the staff to
clear.
.PP
.ps 10
I am already running next month's numbers in my head.
.PP
.ps 10
Fitting my manicured hands to the master controls of the rubbish
factory.
