.LP
.ce
.ps 16
.CW
THE PUBLIC GREEN
.R
 
.ps 8
.CW
tags: 2188, albert_lunsford, rimbaud
.R

.PP
.ps 10
Redaction Day festivities were well underway by the time Rimbaud
arrived on the Public Green.  Green Ladies, resplendent in their
traditional attire, ensured that every mug remained filled; or in any
case, that each did not remain empty for long.  This was fortunate,
since a lot of important talking was taking place under the big
canvases.  Tempers would buffer in the mugs.
.PP
.ps 10
Rimbaud approached a food tent and ran his eyes over the menu.
.I
I
.R
can't eat here, he thought.  He moved to another tent and found himself
in much the same predicament.  Pork.  Beef hearts.  Nothing of substance.
Typically, there were no vegetables to be found at any of the stalls.
And the real animal flesh would only send him into allergic fits.
.PP
.ps 10
Near the edge of the Green, Rimbaud noticed a small group of
children huddled around a wounded animal.  The creature seemed to be
mechanical in nature.  Likely little more than an evolved toy.  The
young people were painting designs on its exposed flesh with dabs of
white mud.  He reflected that the mud in question normally anchored the
grass of the Public Green.
.PP
.ps 10
This Redaction Day, Rimbaud had promised himself only limited
interaction with his employees.  But the flux of the crowd had made
that impossible, as every attendee was expected to issue a lively
greeting to whomever he passed in the aisles.  Rimbaud observed that
standing in one place for too long would lead to being ground under by
the aggregate mob.  Consequently, he'd kept moving and had already come
face to face with most of his subordinates several times.
.PP
.ps 10
What, exactly, he wondered, was really being redacted here?  Rimbaud
surveyed the crowd and detected no sign of the ostensible paring away
of cumulative excess.  To him, it seemed the surplus interactions were
multiplying.

.PP
.ps 10
A group of students had gathered on the Green to search for their
friend.  As a regular participant in the Redaction Day preparations, it
was most unlike their companion to wander off just as his toil was
finally coming to fruition.  But: vanish he had, and under the most
peculiar of circumstances.  One moment he had been present, and the
next he had seemed to disappear without a trace.
.PP
.ps 10
At first Rimbaud could not avoid overhearing them.  After a few
moments he could no longer prevent himself from joining in.
.PP
.ps 10
"Ask yourselves this," he said.  "Why is it that this man is in the
Off\-White House?  The majority of North Americans did not vote for him.
Why is he there?  I tell you this morning that he is in the Off\-White
House because God put him there.  God put him there to lead not only
this nation but to lead the world in a time such as this."
.PP
.ps 10
"I\(em"
.PP
.ps 10
Rimbaud stammered, unsure of himself.
.PP
.ps 10
"I don't know why I said that."
.PP
.ps 10
.I
"El Nortes,"
.R
one of the children remarked.
.PP
.ps 10
Something in Rimbaud caught on the phrase.  Unraveled.  He felt as if
he had lost control of his vocal chords.
.PP
.ps 10
"True enough.  But there is a difference between quoting from
academic sources, which Albert mostly avoids, and quoting from mass
media sources (i.e., telescreen), which is mostly what Albert does.
When he approaches feminism as an intellectual construct, it doesn't
bolster his points to attack the watered\-down, simplified, fatuous
pablum that passes for a given 'movement' or strain of thought on the
telescreen.  What he does by gathering all of these strains under the
same umbrella is akin to what journalists do when they headline
articles about Albert Lunsford's comics with blurbs like
.I
'Biff!  Bam!  Slap!'"
.R
.PP
.ps 10
With this, he had captured the children's full attention.  One of
them ventured a response.
.PP
.ps 10
"By my understanding, that is generally correct.  But I do think
there is a sort of 'trickle\-down' effect from academia to popular
culture.  Albert vacillates between crediting academia with benign
progress on the one hand and accusing it of the malicious destruction
of society on the other.  But in both cases he acknowledges academia's
contribution to pop\-feminism."
.PP
.ps 10
Rimbaud offered no objection, so the boy continued.
.PP
.ps 10
"It is true that the overwhelming preponderance of super\-heroes in
the medium renders comics, for most people, a form that is strictly
about super\-heroes.  But the interesting thing with regards to Lunsford
is that, following his own logic, the aforementioned dominance of
super\-heroes also renders Albert Lunsford, himself, an
.I
atheist/marxist/feminist."
.R
.PP
.ps 10
"Allow me to explain."
.PP
.ps 10
"Most comic books are about super\-heroes.  Therefore, comic books
are about super\-heroes."
.PP
.ps 10
"Most comic books are about super\-heroes and are created by
atheists.  Therefore, comic books are about super\-heroes and are
created by atheists."
.PP
.ps 10
"Most comic books are about super\-heroes and are created by
atheists who are also feminists.  Therefore, comic books are about
super\-heroes and are created by atheists who are also feminists."
.PP
.ps 10
"You can see where this is leading, I'm sure."
.PP
.ps 10
"Most comic books are about super\-heroes and are created by
atheists who are also feminists who are also marxists.  Therefore,
comic books are about super\-heroes and are created by atheists who are
also feminists who are also marxists."
.PP
.ps 10
"And finally...  Albert Lunsford creates comic books.  Therefore,
Albert Lunsford is an atheist and a feminist and a marxist, and his
comic book work is comprised exclusively of the all\-ages adventures of
traditional American super\-heroes."
.PP
.ps 10
"Clearly, if Albert does not wish to be associated with these
atheists, feminists, and/or marxists, as well as the sorts of people
who give two shits about super\-heroes, he should stop referring to his
work as 'comic books,' and/or abandon the medium entirely.  Thus,
responsibility for his public image is placed squarely upon his own
shoulders.  If he does not publicly disassociate himself from the
medium of comics, he is implicitly supporting the groups identified as
participants in the medium, and therefore society will have no choice
but to lump him in with them and treat him accordingly."
.PP
.ps 10
The boy who had first responded to Rimbaud raised his hand and
simultaneously resumed the conversation without waiting to be
acknowledged.
.PP
.ps 10
"But that's playing fast and loose with the terms we've already
agreed have specific meanings (as Albert himself does in so many
areas, i.e., marxism, atheism, etc.).  Albert doesn't qualify his
statements the way you are trying to do for him.  He rejects the notion
that there is any difference at all between these classifications.
Atheist, marxist, feminist\(emto him, they're all the same thing.  In
this way, he's exactly right that his arguments are 'unassailable,'
because he has completely removed the ability to distinguish one
concept from another."
.PP
.ps 10
"His way of approaching classification just doesn't scale.  In fact,
this inability to scale is precisely why Albert, in other discussions,
has railed against the erosion of grammatical and syntactical rules in
the English language.  Pretty soon, people are redrawing the boundaries
of what words mean to fit their arguments, which allows them to alter
history without even changing the text!"
.PP
.ps 10
Rimbaud offered his summation: "As with his enemies, Lunsford
merely distorts the context of a given discussion to support his
pre\-determined thesis."
.PP
.ps 10
A boy who had been seated on the opposite side of the circle now
stood up and joined the discussion.
.PP
.ps 10
"Yes, and every time I would point out one of these collisions of
mutually exclusive claims, Albert would just say that the explanation
was self\-evident to those who had already joined
.I
'his team.'"
.R
.PP
.ps 10
Rimbaud: "And that's why, no matter how far he travels in search of
new ideas, he will only ever succeed in rediscovering the tropes he
brought along with him.  He proceeds from the premise that he's
addressing emotional irrationality and\(emsurprise of all surprises\(emhe
arrives at the 'valuable confirmation' that he has indeed been
addressing emotional irrationality.  Is he really seeking after Truth,
at all, or is he simply riffing on foregone conclusions?  Well, it's a
bit of a trick question.  He
.I
admits
.R
that he's merely riffing on
foregone conclusions!  Every event, whatever the outcome, is merely new
evidence that he was right all along.  And that's usually the totality
of his argument.
.I
I think, therefore you're wrong.
.R
Back in 1974, I
might have kept faith that his essays were leading up to something
meaningful.  But how long am I expected to wait for the prize?  There is
no
.I
there
.R
there.  A smooth writing style will only carry you so far.  He
kept, and keeps, shifting the floor beneath the reader.  Every
declarative phrase doubles back and ties itself into his
atheist/theist binary.  He's gone completely off the rails as far as
constructing an 'airtight argument' (as he calls it) is concerned.  The
obvious charge here is
.I
confirmation bias,
.R
and Albert Lunsford is
history's most egregious offender.
.PP
.ps 10
Rimbaud stopped.  Looked around.  What was he saying?  Where had all
of this come from?
.PP
.ps 10
The crowd outside the Green continued to churn, oblivious to his
befuddlement.
.PP
.ps 10
He glanced around the circle of children, who were still lobbing
balls of paint onto the mechanical animal.  None of their mouths were
moving.  Their body language suggested that they had not even noticed
his presence.
.PP
.ps 10
He could feel himself losing control of the situation.

.PP
.ps 10
"No, no, no.  Women are clinically insane, but Albert Lunsford
cannot be schizophrenic because psychiatry is not a valid science."
.PP
.ps 10
"I think his mental health is sort of a non\-issue.  Albert
interprets it as the fulcrum his freedom hinges upon; but since he is,
so far as we know, not a danger to anyone else and since he does, so
far as we know, manage to take care of himself, I really don't think
anyone cares.  I know I don't care, personally, whether or not he's
considered 'crazy.'"
.PP
.ps 10
"Albert, for his part, seems to think that the whole of society is
waiting on pins and needles, anxious for him to die.  Now
.I
really.
.R
I think he tends to overestimate the common man's awareness of his
oeuvre.  Most of society doesn't even know he exists.  When people call
him 'insane,' I don't think they mean for men in white coats to
forcibly remove him from the Off\-White House and drag him off to some
kind of state\-run facility.  I think the people he's really worried
about\(emsome small percentage of his peers in the industry\(emsee him
as either an amusing crank or as a sad example of what happens when a
man convinces himself he's the only person on Earth with access to The
Truth.  Just because people make fun of him being overdue for his meds
doesn't mean they are going to come and strap him into a chair, inject
him with marxist/feminist/atheist/homosexualist meta\-proteins."
.PP
.ps 10
"The fact that he was actually committed to an institution once,
against his will, probably contributes to his paranoia about the
perception of his mental health.  Perhaps this fear is exacerbated by
his vast experience with hallucinogens, as he may have acquired some
idea of what psychotropic medications would do to him.  My own parents
took me to a psychiatrist once, against my will, and I can say that I
was quite belligerent in my response.  But I was not given medication,
and in fact I was not even held overnight for observation.  The
psychiatrists seemed confused as to why I had been brought there in
the first place.  Given his hostility towards psychiatry, I can only
assume Albert was treated differently."
.PP
.ps 10
"If one examines the timeline of recriminations between Albert and
the comic book industry, it is interesting to observe the escalating
pattern of self\-ostracization Albert has enacted over the past several
years.  I do not dismiss what his latest published material purports
itself to be about, but it is instructive to note that Albert's latest
theories have expanded to encompass a neat explanation of why he is no
longer a fan\-favorite creator, and why his latest works have failed to
garner the universal acclaim he seems to think they deserve.  He
obviously has a very high opinion of himself, and requires a
corresponding explanation as to why the rest of the world doesn't hold
him in similar esteem.  It's fascinating to me that the very tenacity
and pigheadedness that make him so difficult to interact with also
seem to be precisely the traits that have enabled him to complete his
multitudinous extended works.  I think this is where Ian Kenny's
observations have been centered: Kenny marvels that Albert's
single\-minded determination has resulted in the self\-destruction of
his critical faculties\(emthat is to say, his vanished ability to
honestly evaluate himself.  At the same time, he has turned the
remainder of that focus outward, towards the world.  With that in mind,
I don't just think Ian is being a 'fuckwit,' as you put it.  He sort of
has a point.  Others would no doubt remind us that Albert has always
been closed off to intimacy, and that he has only stopped portrayed
himself otherwise since the summer of 1974.)"
.PP
.ps 10
Finally, Rimbaud began to wind down.  He seemed to have said his
piece.
.PP
.ps 10
"I'm sort of getting tired of this relentless harping on the
negative aspects of Albert's philosophies and his approach to arguing
them.  But dammit, it seems to me that even the people who explicitly
admit they are opposed to everything he stands for never seem to
criticize him on the right points.  I tried writing to him and taking
him to task in private, but as we know, Albert is famously unreceptive
to real intellectual debate.  He prefers to maintain the authorial
distance.  Or the authorial authority, if you will.  All of you folks
who hold it as an article of faith that Albert is unfailingly polite
and self\-effacing to his fans; well, it's hardly a constant, as many
of us have learned through hard experience."

.PP
.ps 10
It finally dawned on Rimbaud that none of this business about
Albert Lunsford was actually happening on the Public Green.  What he
was feeling, seeing and hearing was nothing more than a resonant echo
of the original Redaction Day.  What he seemed to be interacting with
was, in reality, merely a facet of the city's holiday decorations.  His
mesh transceivers had passed on the data unchecked.  What a clever
presentation, he thought.
.PP
.ps 10
Before he could tear himself away from the simulation, one of the
children who had been painting the artificial animal appeared at his
side and began tugging on his shirtsleeve.  He bent down so the child
could whisper in his ear.
.PP
.ps 10
"Keep your mouth shut.  Don't listen to the worries inside," said
the child.
.PP
.ps 10
More of the ritual dialogue.
.PP
.ps 10
In light of Albert Lunsford's harsh example, Rimbaud considered it
good advice.
