.LP
.ce
.ps 16
.CW
SHIFT!
.R
 
.ps 8
.CW
tags: 1981, chricton, eva, plinth_mold, tab2
.R

11SEPT1981
.br
UNIVERSAL MOLD, NYC OFFICE

.PP
.ps 10
Plinth Mold scrolled through the morning news and shook his head.
.PP
.ps 10
"They make up some lie and then they get mad at you when you see
through it.  Because in their mind they think they've crafted the
perfect deception, which should appeal to your (perceived) faults."
.PP
.ps 10
"That's pretty fucking ridiculous.  Clearly they are to blame for
their own inability to con you."
.PP
.ps 10
"Yeah."
.PP
.ps 10
"By the way, do you want to come in early today?"
.PP
.ps 10
"I'm already here, sir."
.PP
.ps 10
Plinth looked up from his leaf and saw that Thomas was indeed
standing in the doorway to his office.
.PP
.ps 10
"Oh.  So I'm not talking to you on the phone."
.PP
.ps 10
"No, sir."
.PP
.ps 10
"You sound like you're on the phone."
.PP
.ps 10
"I'm not, sir."
.PP
.ps 10
"You're sure."
.PP
.ps 10
"Yes, sir."

.PP
.ps 10
"Nano\-toxins.  That eat sperm.  Selective genocide."
.PP
.ps 10
"History is spamming
.I
weird."
.R
.PP
.ps 10
"Yeah, I read about it the other day.  Something they unleashed
during World War II.  Hell of a way to get your pipes cleaned."
.PP
.ps 10
"Barbaric.  And yet...  Hmm.  Piques the curiosity."
.PP
.ps 10
"I'll say.  I wonder if it hurts."

.PP
.ps 10
"See if you can finish up these inks before Chricton comes back
from lunch."
.PP
.ps 10
"Will do."
.PP
.ps 10
Thomas moved his fingers inside the box.  Ink lines began to appear
over the blue wireframe on his screen.  Once finished, he would export
the flat image to paper.  For some reason, Plinth Mold still preferred
a 2\-D mock\-up for his action figures.  Thomas found the whole get\-up
awkward, but for a paycheck he was willing to oblige.
.PP
.ps 10
"I know this is not what we set out to do with ourselves," Thomas
said to himself as he continued to trace the lines on his screen.
"We've allowed a number of years to slip by, and yet, no clear
progress towards our goals is apparent."
.PP
.ps 10
Just as Thomas was getting into the rhythm of self\-deprecation,
Chricton returned, bursting through the door with two brown paper bags
full of groceries.
.PP
.ps 10
"That was quick."
.PP
.ps 10
"Yes.  I ran into Eva in the corridor.  Relieved her of these.  Here,
let's snack while we work."

.PP
.ps 10
"Thoughtful of you."
.PP
.ps 10
"Yeah, I don't think she was going to do anything important with
all this stuff anyway.  She was covered in some kind of white powder.
Just stood there while I took her groceries away from her.  Distant
look in her eyes."
.PP
.ps 10
Thomas leaned his head down on his drawing surface and pretended to
snort a line of cocaine.
.PP
.ps 10
Both men laughed heartily.

.PP
.ps 10
Plinth was flossing with a piece of o\-ring from one of the
prototype figures.
.PP
.ps 10
"Boss, that's gross."
.PP
.ps 10
"Hey, all this junk is mine anyway.  Keep your eyes on your own
paper."

.PP
.ps 10
"You know, I've often wondered how to solve the problem of The
Troll."
.PP
.ps 10
"What the fuck is a Troll, boss?"
.PP
.ps 10
"I'm glad you asked.  A Troll is merely someone who enters into a
discussion with the intent of disrupting the equilibrium; usually by
misrepresenting his own or others' actual positions in favor of
inflammatory rhetoric, or by the constant interjection of
.I
non sequiturs."
.R
.PP
.ps 10
"I see.  This has to do with one of your theological speculations,
doesn't it?  Doesn't sound like a very friendly habit, anyway."
.PP
.ps 10
"No, the Troll isn't a very friendly sort at all.  In fact, the
practice of Trolling is usually undertaken maliciously.  Why, the
history of the Green is positively
.I
peppered
.R
with examples of
individuals who\(em"
.PP
.ps 10
"But boss, why would someone want to
.I
do
.R
something like that?  Seems
counterproductive."
.PP
.ps 10
"That, Thomas, is the problem of the Troll."

.PP
.ps 10
Chricton looked up from his workbench.  "I think we should make a
figure of this
.I
Troll
.R
character." He swiveled his screen around and
displayed his design: a small creature with an obnoxious outgrowth of
wispy hair, mounted atop a pencil as if it were some kind of
ornamental eraser.
.PP
.ps 10
Plinth was visibly amused.  He depressed a switch inside his coat
sleeve.
.PP
.ps 10
"Capital idea, Chricton!  Our only obstacle will be securing a
license on the concept from the
.I
Green Consortium."
.R
.PP
.ps 10
All of the men chuckled hesitantly before deliberately shifting the
discussion to other matters.
.PP
.ps 10
The
.I
Green Consortium
.R
never issued licenses.
.PP
.ps 10
Not to the likes of Plinth Mold.
