.LP
.vs 16 \" adjust line spacing for title
.ce 3
.ps 16
.CW
YOU ARE NOT A GADGET,
.br
HE CLAIMED, VIA
.br
CELLPHONE
.R
 
.ps 8
.CW
tags: 1990, eva_bright, freeway_ricky_ross, jaron_lanier, ken_thompson, piro, tab1, tab2
.R
.ps 10

.br

.ce
.ps 10
.B 1

.PP
.ps 10
Dreamed I was a tomcat.
.PP
.ps 10
Trundling along the side of the road, fur matted with dirty snow.
Searching for illegal narcotics.
.PP
.ps 10
My women were nowhere to be found.
.PP
.ps 10
Which was fine.
.PP
.ps 10
I happened to be armed.  As I ambled along, a car sped by and
splashed sludge in my face.  I fired three rounds into its rear\-right
tire and the driver went over an embankment.  An excruciating crashing
noise followed.  It rang in my ears.
.PP
.ps 10
I approached the vehicle and emptied the rest of my weapon into the
driver's chest.
.PP
.ps 10
I found part of a hollowed out cantaloupe and slipped it over my
head.
.PP
.ps 10
Cute.
.PP
.ps 10
No one would prosecute a Persian cat.

.ce
.ps 10
.B 2

.PP
.ps 10
"Oh, great."
.PP
.ps 10
"What?"
.PP
.ps 10
"I accidentally saved an image of Spider\-Man in my porn folder."
.PP
.ps 10
"So?  Move it.  Or delete it."
.PP
.ps 10
"But I clicked 'Save' without seeing the name of the file."
.PP
.ps 10
"So?"
.PP
.ps 10
"So, how am I supposed to find it?  This folder is 5TB.  I don't want
that Spider\-Man image to someday be found amongst my archival porn."
.PP
.ps 10
"So, go back and start to save it again and see what the suggested
filename is.  You probably just hit 'Enter' when you saved it."
.PP
.ps 10
"That...  is a very good idea."
.PP
.ps 10
"I think I once helped your dad with a similar problem."

.ce
.ps 10
.B 3

.PP
.ps 10
Jaron Lanier scooped up a handful of the white powder and inspected
it closely.
.PP
.ps 10
"This appears to be cocaine."
.PP
.ps 10
"No shit, Lanier," said Piro.
.PP
.ps 10
Lanier peered into his hand, face wrinkled in concentration.
.PP
.ps 10
Piro turned to Thomas.  "He's always like this."
.PP
.ps 10
"He doesn't get high out of our supply, does he?"
.PP
.ps 10
Piro stopped Thomas before he went any further with that line of
thought.
.PP
.ps 10
"No.  At least, not that I'm aware."

.ce
.ps 10
.B 4

.PP
.ps 10
It turned out that my son had the drugs.
.PP
.ps 10
.I
Nepeta cataria.
.R
Fifty grams.  I'm certain his intent was to sell.
.PP
.ps 10
I left ten grams with an I.O.U.
.PP
.ps 10
The rest I put in my nose.  I then put on dark sunglasses to mask my
dilated pupils, the visible redness in my eyes.
.PP
.ps 10
A car drove by and its pilot tossed an empty beer can at my head.
It bounced off the cantaloupe and skittered into the grass by the side
of the road.
.PP
.ps 10
I peered at the exhaust trail over the top of my sunglasses.
.PP
.ps 10
Then I pulled out my gun.

.bp
.ce
.ps 10
.B 5

.PP
.ps 10
.PP
.ps 10
It was Ken on the phone.
.PP
.ps 10
"Lanier, I need some help with these verb tenses."
.PP
.ps 10
"Not now, Ken, we're...  weighing...  the drugs."
.PP
.ps 10
Piro snatched the phone away from him and barked into the
mouthpiece.
.PP
.ps 10
"Ken!  Not on this phone!"
.PP
.ps 10
He jammed his thumb on the 'End' button and then turned back to
Lanier.
.PP
.ps 10
"Are you
.I
damaged?
.R
He can study on his own time!"
.PP
.ps 10
"Sorry, sorry," said Lanier, taking a kilo off of the scales.
.PP
.ps 10
Piro extracted the SIM card from the phone and crushed it in his
hand.
.PP
.ps 10
"Card," he said.
.PP
.ps 10
Ricky tossed him a replacement and Piro snapped it into place,
booted up the phone.  He dialed New York.
.PP
.ps 10
"Eva, patch me through to Nicaragua."
.PP
.ps 10
Some moments passed and then Piro began shouting into the
mouthpiece in gutter Spanish.  He rung off and handed the phone back to
Lanier.
.PP
.ps 10
"Don't lose that."
.PP
.ps 10
Thomas finished with his baggies and then dusted off his hands.
.PP
.ps 10
"Ken's obsession with Japanese culture is becoming a problem.  He
can't keep his mind on his work.  Someone needs to ship him back to
Japan."
.PP
.ps 10
Piro rolled his eyes.  Not for the first time that day.
.PP
.ps 10
"His parents don't
.I
want
.R
him back.  At least not until he learns to
speak Japanese."
.PP
.ps 10
"Huh.  That seems unlikely to happen.  Couldn't we just do fansubs
for them?"
.PP
.ps 10
The men all shared a laugh and then got back to work.

.bp
.ce
.ps 10
.B 6

.PP
.ps 10
.PP
.ps 10
Ken unpaused and then re\-paused the DVD.
.PP
.ps 10
He was at an impasse.  The episode of
DOUBLE CATS\f(CW™\fR
was only a quarter
of the way through, but he was having trouble understanding the
dialogue.  Finally, he had given up and called Lanier for help.
.PP
.ps 10
He was supposed to be translating these episodes for the torrent
site.
.PP
.ps 10
How could he admit that as a native Japanese, he couldn't even
speak his own language?
.PP
.ps 10
His mind raced.  Activating his super\-speed, he cleaned up his
apartment and did the dishes in just under four seconds, moving so fast
he knocked over a bookshelf and had to re\-shelve the books.  This added
another two seconds to the tally.  He started a pot of spaghetti noodles
boiling and took some wine out of the refrigerator.  Another
half\-second.
.PP
.ps 10
The impending public humiliation would surely kill him.
.PP
.ps 10
Unexpectedly, the phone rang.
.PP
.ps 10
"Ken."
.PP
.ps 10
It was Lanier.
.PP
.ps 10
"I can't stay on here long, but let hear some of the phrases and
I'll give you some quick translations."
.PP
.ps 10
"All right, the cat is wearing a cantaloupe on its head, it just
pulled out a gun and shot out the tires of a car.  The car went into a
ditch and crashed.  Now the cat is smoking a cigarette and putting on a
pair of sunglasses.  The cat says:
.I
Baka."
.R
.PP
.ps 10
Lanier paused before answering.
.PP
.ps 10
"What...  What exactly are we translating here?"
.PP
.ps 10
"It's an anime.  I'm supposed to be doing fansubs.  I committed to
the first six episodes by tonight."
.PP
.ps 10
"That's a lot of work, Ken.  You're not a gadget, you know."
.PP
.ps 10
"Yeah, but geeze, shouldn't I at least be able to handle this?  I
didn't even start learning English until I was six years old.  How could
I have completely forgotten my own language?"
.PP
.ps 10
"Uh, I've gotta go."
.PP
.ps 10
Lanier hung up.

.ce
.ps 10
.B 7

.PP
.ps 10
"What are you doing?  Give me the phone."
.PP
.ps 10
Piro took the cellphone and stuffed it in his jacket pocket.  He
pushed Lanier out of the way and then locked the door to the kitchen.
.PP
.ps 10
"Thomas.  Set the timers.  We need a good twenty minutes to get out
of the neighborhood."
.PP
.ps 10
Thomas set all the detonators and the team evacuated the little
house.
.PP
.ps 10
"Maybe I should call dad," he said, once he had finished loading up
his gear.
.PP
.ps 10
"Why?"
.PP
.ps 10
"He might have some good ideas about how to..." Now it was Thomas'
turn to roll his eyes.  "Oh,
.I
never mind."
.R
.PP
.ps 10
The men climbed into their white van and pulled away from the safe
house.  As the vehicle accelerated into traffic, Lanier began to
scribble in his notebook.
.PP
.ps 10
Piro gestured towards him, frowning.
.PP
.ps 10
"I don't want this guy coming along with us next time."
.PP
.ps 10
"What did
.I
I
.R
do," Lanier protested.
.PP
.ps 10
"Shut up," the rest of the men said in unison.
.PP
.ps 10
"This is a business," Piro began.  "There's not time for dicking
around with language studies and sketching portraits."
.PP
.ps 10
Thomas pretended to ignore the scene from behind his visor.  He
brought up some sports scores and wondered at the meticulous
pointlessness of the statistics industry.
.PP
.ps 10
"Huh.  It looks like the Bears have taken the Super Bowl."
.PP
.ps 10
The van hit a bump and for a split second Thomas' visor slid up and
exposed his face.
.PP
.ps 10
"Oh God, what's wrong with his eyes?" asked Lanier.
.PP
.ps 10
Thomas stuck out his tongue and went back to scanning the news.
