APE=/sys/src/ape
<$APE/config

LIB=/$objtype/lib/ape/libsec.a

OFILES=
HFILES=/sys/include/ape/libsec.h

</sys/src/cmd/mksyslib

%.$O:	/sys/src/libsec/$objtype/%.s
	$AS $AFLAGS /sys/src/libsec/$objtype/$stem.s
