</$objtype/mkfile

TARG=serial
OFILES=ftdi.$O serial.$O prolific.$O ucons.$O silabs.$O ch340.$O
HFILES=\
	../lib/usb.h\
	serial.h\

LIB=../lib/usb.a$O

BIN=/$objtype/bin/nusb

</sys/src/cmd/mkone

CFLAGS=-I../lib $CFLAGS
