APE=/sys/src/ape
<$APE/config

LIB=/$objtype/lib/ape/libmp.a

HFILES=\
	/sys/include/ape/mp.h\
	../../../../libmp/port/dat.h

</sys/src/cmd/mksyslib

%.$O:	../../../../libmp/power64/%.s
	$AS ../../../../libmp/power64/$stem.s
