objtype=mips
</$objtype/mkfile

LIB=/$objtype/lib/libmp.a
SFILES=\
	mpvecadd.s\
	mpvecsub.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\
#	mpdigdiv.s\

HFILES=/$objtype/include/u.h /sys/include/mp.h ../port/dat.h

OFIL
</sys/src/cmd/mksyslib
