</$objtype/mkfile

TARG=syscall
OFILES=syscall.$O\

HFILES=tab.h\

BIN=/$objtype/bin

</sys/src/cmd/mkone

SYSCALL=/sys/src/libc/9syscall/sys.h

tab.h:	$SYSCALL mktab.awk
	./mktab.awk $SYSCALL >$target

clean:V:
	rm -f *.[$OS] [$OS].out $TARG $HFILES
