</$objtype/mkfile

TARG=tc
OFILES=	cgen.$O\
	enam.$O\
	list.$O\
	mul.$O\
	peep.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\

HFILES=\
	gc.h\
	../5c/5.out.h\
	../cc/compat.h\
	../cc/cc.h\

T=5
<../cc/mkfile.port
</sys/src/cmd/mkone
