</$objtype/mkfile

LIBFILES=\
	error\
	file\
	glob\
	pack\

LIB=${LIBFILES:%=%.$O}

HFILES=\
	/sys/include/venti.h\
	stdinc.h\
	error.h\
	vac.h\
	dat.h\
	fns.h\

TARG=vac unvac vacfs
BIN=/$objtype/bin

default:V: all

</sys/src/cmd/mkmany
